id: P000350
initial_creation_type: ocr
created_at: 14/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2PD17637
  title: རབ་བྱུང་བཅུ་བདུན་པའི་ཤིང་ལུག་ལོའི་ལོ་ཐོ། སྤྱི་ལོ ༢༠༡༥ལོ།
  author: ''
  volumes:
    16adced9b2224700a975b89ca59013f9:
      image_group_id: I2PD19276
      title: Volume 1 of rab byung bcu bdun pa'i shing lug lo'i lo tho/ spyi lo 2015lo/
      volume_number: 1
      total_pages: 130
      base_file: v001.txt
